module.exports = [
   {
      name: 'Damian',
      surname: 'Trafiałek',
      gender: 'male',
      height: 181,
      weight: 60,
   },
   {
      name: 'Mateusz',
      surname: 'Karandys',
      gender: 'male',
      height: 174,
      weight: 57,
   },
   {
      name: 'Mateusz',
      surname: 'Brochocki',
      gender: 'male',
      height: 177,
      weight: 64,
   },
   {
      name: 'Marysia',
      surname: 'idk',
      gender: 'female',
      height: 160,
      weight: 50,
   },
   {
      name: 'Kuba',
      surname: 'Giezgała',
      gender: 'male',
      height: 181,
      weight: 61,
   },
   {
      name: 'Kacper',
      surname: 'Przybysz',
      gender: 'male',
      height: 181,
      weight: 63,
   },
   {
      name: 'Gabrysia',
      surname: 'idk',
      gender: 'female',
      height: 165,
      weight: 55,
   },
   {
      name: 'Wojtek',
      surname: 'Wasilewski',
      gender: 'male',
      height: 190,
      weight: 75,
   },
   {
      name: 'Michał',
      surname: 'Rudzki',
      gender: 'male',
      height: 180,
      weight: 63,
   },
];
